# Spring properties
spring:
  application:
     name: web-client
  freemarker:
    enabled: false
  thymeleaf:
    enabled: false

# Discovery Server
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true

# HTTP Server
server:
  port: 8082

management:
  context-path: /monitor