spring:
  application:
     name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_PATH} #${DEV}/Perso/cloud-experiment/config
server:
  port: ${SERVER_PORT:8888}